"""
Live 10-Concurrent Call Capacity & Load Benchmark Test
Spawns 10 simultaneous live call streams against Path C Voice Agent Gateway (Port 9092).
Displays live turn-by-turn text generated by Groq LLM and Cartesia TTS across all 10 channels,
measures latency metrics, and generates master audio mix artifact.
"""

import os
import sys
import time
import wave
import uuid
import struct
import asyncio
import audioop
import numpy as np
from typing import List, Dict, Any

sys.stdout.reconfigure(encoding='utf-8')
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from path_c_hybrid_agent.tts_cartesia import synthesize_speech_hd

HOST = "127.0.0.1"
PORT = 9092

# 10 Concurrent Test Scenario Queries
SCENARIOS = [
    {"id": "Call-01", "phone": "+919811000001", "query": "राम-राम सा! मैं ₹1000 रो डोनेशन देबो चाहूँ।"},
    {"id": "Call-02", "phone": "+919811000002", "query": "80G टैक्स रसीद मिलेगी काई सा?"},
    {"id": "Call-03", "phone": "+919811000003", "query": "माली सैनी समाज सेवा फाउंडेशन रो ऑफिस कहाँ है?"},
    {"id": "Call-04", "phone": "+919811000004", "query": "आपरा मैनेजर सा सूं बात करवाओ।"},
    {"id": "Call-05", "phone": "+919811000005", "query": "डोनेशन नेटबैंकिंग या UPI सूं दे सकां काई?"},
    {"id": "Call-06", "phone": "+919811000006", "query": "फाउंडेशन रा डायरेक्टर्स कुण-कुण हैं?"},
    {"id": "Call-07", "phone": "+919811000007", "query": "राम-राम सा! मैं नया सदस्य बणबो चाहूँ।"},
    {"id": "Call-08", "phone": "+919811000008", "query": "डोनेशन री रसीद ईमेल पर मिलेगी काई सा?"},
    {"id": "Call-09", "phone": "+919811000009", "query": "फाउंडेशन रा काई-काई समाज सेवा काम हैं?"},
    {"id": "Call-10", "phone": "+919811000010", "query": "घणो-घणो धन्यवाद सा! राम-राम।"}
]


async def run_single_call_channel(scenario: Dict[str, str], results_list: List[Dict[str, Any]], pcm_audio_collector: Dict[str, bytes]):
    call_id = scenario["id"]
    phone = scenario["phone"]
    query = scenario["query"]

    t_call_start = time.perf_counter()
    print(f"  🟢 [{call_id}] Connecting channel ({phone})...")

    try:
        reader, writer = await asyncio.open_connection(HOST, PORT)
        
        # 1. Send AudioSocket Header (0x01 UUID)
        u_bytes = uuid.uuid4().bytes
        hdr = struct.pack("!BH", 0x01, 16)
        writer.write(hdr + u_bytes)
        await writer.drain()

        # 2. Receive Initial Greeting Audio from Gateway
        greeting_pcm = bytearray()
        t0_greeting = time.perf_counter()
        while time.perf_counter() - t0_greeting < 2.5:
            try:
                g_hdr = await asyncio.wait_for(reader.readexactly(3), timeout=0.3)
                p_type, p_len = struct.unpack("!BH", g_hdr)
                p_data = await reader.readexactly(p_len)
                if p_type == 0x10:
                    greeting_pcm.extend(p_data)
            except Exception:
                break

        print(f"  📢 [{call_id}] Initial Greeting Received ({len(greeting_pcm)} bytes PCM)")

        # 3. Synthesize Caller Utterance Audio (8kHz PCM 16-bit mono)
        caller_pcm_24k = await synthesize_speech_hd(query, voice_id="791d5162-d5eb-40f0-8189-f19db44611d8", sample_rate=24000)
        if not caller_pcm_24k:
            caller_pcm_24k = b"\x00" * 48000
        
        audio_np = np.frombuffer(caller_pcm_24k, dtype=np.int16)
        caller_pcm_8k = audio_np[::3].tobytes()

        # 4. Stream Caller Audio to Gateway (20ms frames = 320 bytes)
        t_speak_start = time.perf_counter()
        print(f"  🗣️ [{call_id}] Caller Speaking: '{query}'")

        for i in range(0, len(caller_pcm_8k), 320):
            chunk = caller_pcm_8k[i:i+320].ljust(320, b"\x00")
            frame_hdr = struct.pack("!BH", 0x10, 320)
            writer.write(frame_hdr + chunk)
            await asyncio.sleep(0.018)

        await writer.drain()

        # Send ~500ms Silence to trigger VAD turn completion
        silence_chunk = b"\x00" * 320
        for _ in range(25):
            writer.write(struct.pack("!BH", 0x10, 320) + silence_chunk)
            await asyncio.sleep(0.018)
        await writer.drain()

        # 5. Receive Agent Marwadi Response Audio back from Gateway
        agent_response_pcm = bytearray()
        t_wait_resp = time.perf_counter()
        ttft_ms = 0

        while time.perf_counter() - t_wait_resp < 6.0:
            try:
                r_hdr = await asyncio.wait_for(reader.readexactly(3), timeout=0.5)
                p_type, p_len = struct.unpack("!BH", r_hdr)
                p_data = await reader.readexactly(p_len)
                if p_type == 0x10:
                    if len(agent_response_pcm) == 0:
                        ttft_ms = round((time.perf_counter() - t_wait_resp) * 1000, 1)
                    agent_response_pcm.extend(p_data)
            except asyncio.TimeoutError:
                if len(agent_response_pcm) > 0:
                    break
            except Exception:
                break

        total_duration = round(time.perf_counter() - t_call_start, 2)
        print(f"  🤖 [{call_id}] Response Received ({len(agent_response_pcm)} bytes PCM, First Token Latency: {ttft_ms}ms, Total: {total_duration}s)")

        # Send Hangup
        writer.write(struct.pack("!BH", 0x00, 0))
        await writer.drain()
        writer.close()

        pcm_audio_collector[call_id] = bytes(agent_response_pcm)
        results_list.append({
            "call_id": call_id,
            "phone": phone,
            "query": query,
            "ttft_ms": ttft_ms,
            "pcm_bytes": len(agent_response_pcm),
            "status": "SUCCESS"
        })

    except Exception as e:
        print(f"  ❌ [{call_id}] Exception: {e}")
        results_list.append({
            "call_id": call_id,
            "phone": phone,
            "query": query,
            "ttft_ms": 0,
            "pcm_bytes": 0,
            "status": f"FAILED: {e}"
        })


async def main():
    print("=" * 85)
    print("  🚀 STARTING LIVE 10-CONCURRENT CALL CAPACITY BENCHMARK TEST")
    print("  Target Gateway: AudioSocket TCP 127.0.0.1:9092 (Path C Engine)")
    print("=================================================================================\n")

    # Start Gateway Server if needed
    t_start_all = time.perf_counter()
    results: List[Dict[str, Any]] = []
    audio_collector: Dict[str, bytes] = {}

    # Launch 10 simultaneous calls in parallel
    tasks = [run_single_call_channel(sc, results, audio_collector) for sc in SCENARIOS]
    await asyncio.gather(*tasks)

    total_test_time = round(time.perf_counter() - t_start_all, 2)

    print("\n" + "=" * 85)
    print("  📊 10-CONCURRENT CALL BENCHMARK SUMMARY & PERFORMANCE REPORT")
    print("=================================================================================")
    print(f"  Total Test Time: {total_test_time}s")
    print(f"  Total Channels Executed: {len(results)}")
    print(f"  Successful Channels: {sum(1 for r in results if r['status'] == 'SUCCESS')}/10\n")

    print(f"  {'Channel':<10} | {'Phone':<15} | {'TTFT (ms)':<10} | {'Audio Received':<16} | {'Status':<10}")
    print("  " + "-" * 75)
    
    ttfts = []
    for r in sorted(results, key=lambda x: x['call_id']):
        if r['ttft_ms'] > 0:
            ttfts.append(r['ttft_ms'])
        print(f"  {r['call_id']:<10} | {r['phone']:<15} | {r['ttft_ms']:<10} | {r['pcm_bytes']:<16} | {r['status']:<10}")

    if ttfts:
        print(f"\n  ⚡ Average First Token Latency (TTFT) across 10 parallel calls: {np.mean(ttfts):.1f}ms")
        print(f"  ⚡ Max Turn Latency across 10 parallel calls: {np.max(ttfts):.1f}ms")

    # Generate Master Audio Mix Artifact File
    artifact_dir = r"C:\Users\msanj\.gemini\antigravity\brain\3f670608-a148-48ef-8f33-27bc120319d4"
    master_mix_path = os.path.join(artifact_dir, "live_10_concurrent_master_mix.wav")

    max_len = max([len(b) for b in audio_collector.values()] + [0])
    if max_len > 0:
        mix_array = np.zeros(max_len // 2, dtype=np.int32)
        for pcm_b in audio_collector.values():
            if pcm_b:
                arr = np.frombuffer(pcm_b[: (len(pcm_b) // 2) * 2], dtype=np.int16)
                mix_array[:len(arr)] += arr

        # Clip to int16
        clipped_mix = np.clip(mix_array, -32768, 32767).astype(np.int16)

        with wave.open(master_mix_path, "wb") as wf:
            wf.setnchannels(1)
            wf.setsampwidth(2)
            wf.setframerate(8000)
            wf.writeframes(clipped_mix.tobytes())

        print(f"\n  🎵 Live 10-Channel Master Audio Mix Saved to:\n     {master_mix_path}")

    print("=================================================================================\n")

if __name__ == "__main__":
    asyncio.run(main())
